theme: jekyll-theme-minimal



# Setup
title:               Garment Extractor
tagline:             A Work in Progress
url:                 https://claremarie.github.io/garment_extraction/
paginate:            1
baseurl:             ""



# About/contact
author:
  name:              Clare Myers
#  url:               https://twitter.com/mdo
  email:             cmmyers@gmail.com


github:
  repo:              https://github.com/claremarie/garment_extraction/
